### PR TITLE
Issue 41 - test coverage on .gpkg helper function

### PR DESCRIPTION
**Pull request by jlucktay**
I had some trouble running up the base package, so I have split the helper function out into its own sub-package in order to isolate it and write/execute the test coverage across it.

Hope this is OK, and please let me know if there are any changes I need to make. Thanks!

### CODE REVIEW

**Comment by JivanAmara** [comment]
Hi @jlucktay, making an additional package for a single function is a stretch, and putting an additional main.go in it invites confusion about the application's & go_wfs_gpkg's purpose.  Pulling defaultGpkg() out of main.go makes sense to allow it to be tested, but a `utils.go` or `default_gpkg.go` file would make more sense.

**Comment by jlucktay** [comment]
I get that the extra package is overkill, but as I said, I couldn't get the existing main package to run up at all.
There is a segmentation fault that I couldn't get to the bottom of:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x42f27f6]

goroutine 1 [running]:
github.com/jban332/kin-openapi/openapi3.NewOneOfSchema(0xc42005fb30, 0x2, 0x2, 0x4)
	/Users/jameslucktaylor/go/src/github.com/jban332/kin-openapi/openapi3/schema.go:101 +0x76
```

Around line 264 of `/Users/jameslucktaylor/go/src/github.com/jlucktay/go-wfs/wfs3/wfs3_types.go` there is a call like this:
```
"geometry": {
	Value: openapi3.NewOneOfSchema(
		&openapi3.Schema{Type: "null"},
		&openapi3.Schema{
			Properties: map[string]*openapi3.SchemaRef{
				"bbox": {
```
Inside that `NewOneOfSchema()` call is where it all goes bad.

It doesn't matter if I run all package tests, all file tests, or just this one specific test. They all come up with an error like that.

It starts from this import line in the `main` package:
```
import (
	"github.com/jlucktay/go-wfs/wfs3"
```

**Comment by JivanAmara** [comment]
Looks like you snagged a commit that was unstable.  There's a problem w/ that openapi3 package, and that particular use has been removed from this project for that reason.  Try rebasing or merging your branch with the current master, or better yet, branch self_prev_next.

**Comment by jlucktay** [comment]
Thanks for the heads up @JivanAmara!
I branched from `self_prev_next` and re-did the tests.
Going to close this PR and open another from my new branch.

**Pull request closed without merging**
